module.exports={
    accountRegistrationPagePartialUrl: 'registration',
    niceToMeetYouuMsg: 'Nice to meet you',
    enterMandatoryFieldsError:'Please select',
    accountRegistrationSuccessMsg:'Your account is all set up!',
    nrtKitQuestion: 'Where should we ship your NRT Quit Kit?',
    q4lGetStartedPageHeading:'Quit For Life',
    q4lFinalizeAccountPageHeading:'finalize your account',
    q4lBenifit1Title: 'Program Length',
    q4lBenifit1Desc: '6-8 weeks',
    q4lBenifit2Title: 'Time Commitment',
    q4lBenifit2Desc: 'Meet 15-30 minutes',
    q4lBenifit3Title: 'Coach Support',
    q4lBenifit3Desc: '1-on-1 calls and live online group sessions',
    q4lSurverQuestion1:'How ready are you to quit',
    q4lSurverQuestion2:'Quit Date',
    q4lSurverQuestion3:'How coaches help you quit',
    q4lSurverQuestion4:'When are good weekday times to call you?',
    q4lSurverQuestion5:'Got it! When are good weekend times to call you?',
    q4lSurverQuestion6:'best number to call?',
    q4lSurveySubimissionSuccess:'Fantastic! Here are your next steps.',
    dashboardStep1:'Getting Ready to Quit',
    card1CoachMessage: 'Call 866-784-8454',
    card3TextACoachMediaCard:'Help is just a text away',
    card4BonusAction:'Make a list of your reasons for quitting'
};